### PR TITLE
support Python 3.11

### LINKED ISSUE #43: backport contextlib from python 3.12
https://github.com/python/cpython/commit/6cb145d23f5cf69b6d7414877d142747cd3d134c

> A TypeError is now raised instead of an AttributeError in contextlib.ExitStack.enter_context() and contextlib.AsyncExitStack.enter_async_context() for objects which do not support the context manager or asynchronous context manager protocols correspondingly. (Contributed by Serhiy Storchaka in bpo-44471.)

however this is only to match the change in behaviour of the `async with` and `with` statements in 3.11:

> A TypeError is now raised instead of an AttributeError in with and async with statements for objects which do not support the context manager or asynchronous context manager protocols correspondingly. (Contributed by Serhiy Storchaka in bpo-12022.)

so would need conditional checking.

perhaps:

```python
if sys.version_info >= (3, 11):
    from contextlib import ExitStack, AsyncExitStack
else:
    class ExitStack(...):
        ...

    class AsyncExitStack(...):
        ...
```

would be best?

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #43

### CODE REVIEW

**Comment by mikegerber** [comment]
I was looking for this (specifically a port of 3.11's `chdir()` context manager.) today.

Would testing/reviewing this PR help with merging this?

**Review by ncoghlan — CHANGES_REQUESTED** [review]
Sorry for the spectacularly long hiatus on PR reviews. No worries if this is no longer on your todo list, I can take it and make the required cleanups.

**Comment by mr-c** [comment]
I am happy to hand this over to you @ncoghlan :+1: , thanks!

**Comment by ncoghlan** [comment]
Given the amount of time that's elapsed since the last update, I'm going to skip straight to the Python 3.13 beta branch (this is technically syncing to 3.12.1, since the last contextlib change was https://github.com/python/cpython/issues/103791, which landed in 3.12.1 and 3.13.0a2).

**Comment by mr-c** [comment]
Thank you Alyssa; I'm one of the maintainers of the contextlib2 package for Debian; let me know if you've got a release candidate and I can upload it to Debian experimental to check for regressions with respect to our other packages

**Pull request closed without merging**
